FROM gimnemo/httpd:1.0

ENV REPO=static-web-template
ENV TAG_VERSION=1.1

RUN curl -LJO http://github.com/ksj1428/${REPO}/archive/refs/tags/v${TAG_VERSION}.tar.gz
RUN tar -zxvf ${REPO}-${TAG_VERSION}.tar.gz
RUN mv ${REPO}-${TAG_VERSION}/htdocs/* /usr/local/apache2/htdocs/