apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    name: secret-pod
spec:
  containers:
  - name: secret-pod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: PASSWORD 
      valueFrom:
        secretKeyRef:
          name: secret-config
          key: password 
    envFrom:
    - secretRef:
        name: secret-config
    volumeMounts:
    - name: secret-voulme
      mountPath: /config
      readOnly: true
  volumes:
  - name: secret-voulme
    secret:
      secretName: secret-config
  imagePullSecrets:
  - name: docker-pull-secret
