apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-httpd-static-web
spec:
  selector:
    matchLabels:
      app: static-web
      version: "2.0"
      server: httpd
      date: "2023-07"
  replicas: 0
  template:
    metadata:
      labels:
        app: static-web
        version: "2.0"
        server: httpd
        date: "2023-07"
    spec:
      containers:
      - name: httpd-static-web
        image: gimnemo/httpd:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-pull-secret