apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-static-web
spec:
  selector:
    matchLabels:
      app: static-web
      version: "1.0"
      server: nginx
      date: "2023-07"
  replicas: 3
  template:
    metadata:
      labels:
        app: static-web
        version: "1.0"
        server: nginx
        date: "2023-07"
    spec:
      containers:
      - name: nginx-static-web
        image: gimnemo/nginx:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-pull-secret