apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
  labels:
    name: vol-pod
spec:
  containers:
  - name: vol-pod
    image: nginx
    ports:
      - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"        
    volumeMounts:      
    - name: volume1      
      mountPath: /usr/share/nginx/html 
  volumes:
  - name: volume1   
    nfs:
      path: /mnt/nfs_share1 
      server: 192.168.10.14 
      readOnly: true 
  imagePullSecrets: 
  - name: docker-pull-secret