apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: pod-name
spec:
  containers:
  - name: container-name
    image: quay.io/nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
