apiVersion: v1
kind: Pod
metadata:
  name: web-pod-nginx
  labels:
    app : web
    app-type : nginx
spec:
  containers:
  - name: container-name
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  imagepullsecrets:
  - name: docker-pull-secret

---

apiVersion: v1
kind: Pod
metadata:
  name: web-pod-httpd
  labels:
    app : web
    app-type : apache
spec:
  containers:
  - name: apache-container
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
  imagepullsecrets:
  - name: docker-pull-secret